# Generated by Django 4.0.4 on 2022-05-08 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_document', models.CharField(max_length=14, verbose_name='CNPJ da empresa')),
                ('company_name', models.CharField(max_length=255, verbose_name='nome da empresa')),
                ('company_registration', models.CharField(max_length=255, verbose_name='inscrição estadual')),
                ('client_name', models.CharField(max_length=255, verbose_name='nome do cliente')),
                ('client_document', models.CharField(max_length=14, verbose_name='CPF / CNPJ do cliente')),
                ('client_address', models.CharField(max_length=255, verbose_name='endereço do cliente')),
                ('service_description', models.CharField(max_length=255, verbose_name='descrição')),
                ('canceled', models.BooleanField(default=False, verbose_name='cancelada')),
                ('payment_method', models.CharField(choices=[('À Vista', 'À Vista'), ('Boleto', 'Boleto'), ('Cartão de crédito', 'Cartão de crédito'), ('Cartão de Débito', 'Cartão de Débito')], default=1, max_length=255, verbose_name='método de pagamento')),
                ('invoice_date', models.DateField(auto_now_add=True, verbose_name='data de fatura')),
                ('total', models.FloatField(blank=True, null=True)),
                ('sent', models.BooleanField(default=False, editable=False)),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.serviceorder', verbose_name='ordem de serviço')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
                ('cost', models.CharField(max_length=255, verbose_name='custo')),
                ('service_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.serviceinvoice')),
            ],
        ),
    ]
