# Generated by Django 4.0.4 on 2022-05-07 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_serviceorder_sponsor_employee'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinvoice',
            name='service_order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='service.serviceorder', verbose_name='ordem de serviço'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceinvoice',
            name='payment_method',
            field=models.CharField(choices=[('À Vista', 'À Vista'), ('Boleto', 'Boleto'), ('Cartão de crédito', 'Cartão de crédito'), ('Cartão de Débito', 'Cartão de Débito')], default=1, max_length=255, verbose_name='método de pagamento'),
        ),
    ]
