# Generated by Django 4.0.4 on 2022-05-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_serviceinvoice_service_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceinvoice',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
