# Generated by Django 4.0.4 on 2022-05-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_serviceinvoice_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinvoice',
            name='sent',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
