# Generated by Django 4.0.4 on 2022-05-05 01:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('total_cost', models.FloatField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('entrance_date', models.DateField(default=django.utils.timezone.now)),
                ('departure_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
        ),
    ]
