# Generated by Django 4.0.4 on 2022-05-08 03:16

import apps.inventory.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'serviço',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='descrição')),
                ('cost', models.FloatField(verbose_name='custo')),
            ],
            options={
                'verbose_name': 'item de serviço',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_date', models.DateField(default=django.utils.timezone.now, verbose_name='data de entrada')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='data de saída')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.client', verbose_name='cliente')),
                ('company', models.ForeignKey(default=apps.inventory.models.Company.object, on_delete=django.db.models.deletion.PROTECT, to='inventory.company', verbose_name='Empresa')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.service', verbose_name='serviço')),
                ('sponsor_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='funcionário responsável')),
            ],
            options={
                'verbose_name': 'ordem de serviço',
            },
        ),
        migrations.CreateModel(
            name='ServiceItemOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False, verbose_name='finalizado')),
                ('service_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.serviceitem', verbose_name='item de serviço')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.serviceorder', verbose_name='ordem de serviço')),
                ('sponsor_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='funcionário designado')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='service_items',
            field=models.ManyToManyField(blank=True, help_text='Segure <i>Shift</i> para selecionar mais de um item', to='service.serviceitem', verbose_name='itens'),
        ),
    ]
