# Generated by Django 4.0.4 on 2022-05-05 23:47

import apps.inventory.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_employee_admission_date'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='serviceitem',
            name='service',
        ),
        migrations.AddField(
            model_name='service',
            name='service_items',
            field=models.ManyToManyField(blank=True, to='service.serviceitem', verbose_name='itens'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=100, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='cost',
            field=models.FloatField(verbose_name='custo'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='description',
            field=models.CharField(max_length=100, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='serviceitemorder',
            name='service_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.serviceitem', verbose_name='item de serviço'),
        ),
        migrations.AlterField(
            model_name='serviceitemorder',
            name='service_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.serviceorder', verbose_name='ordem de serviço'),
        ),
        migrations.AlterField(
            model_name='serviceitemorder',
            name='sponsor_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.employee', verbose_name='funcionário designado'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.client', verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='company',
            field=models.ForeignKey(default=apps.inventory.models.Company.object, on_delete=django.db.models.deletion.PROTECT, to='inventory.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de saída'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='entrance_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='data de entrada'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.service', verbose_name='serviço'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='sponsor_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.employee', verbose_name='funcionário designado'),
        ),
    ]
