# Generated by Django 4.0.4 on 2022-05-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_service_total_cost_remove_serviceitem_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_items',
            field=models.ManyToManyField(blank=True, help_text='Segure <i>Shift</i> para selecionar mais de um item', to='service.serviceitem', verbose_name='itens'),
        ),
    ]
