# Generated by Django 4.0.4 on 2022-05-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_service_service_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'serviço'},
        ),
        migrations.AlterModelOptions(
            name='serviceitem',
            options={'verbose_name': 'item de serviço'},
        ),
        migrations.AlterModelOptions(
            name='serviceorder',
            options={'verbose_name': 'ordem de serviço'},
        ),
        migrations.AddField(
            model_name='serviceitemorder',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='finalizado'),
        ),
    ]
