# Generated by Django 4.0.4 on 2022-05-07 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0004_alter_service_options_alter_serviceitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='sponsor_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='funcionário responsável'),
        ),
    ]
