# Generated by Django 4.0.4 on 2022-05-10 00:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('speciality', models.CharField(max_length=100, verbose_name='especialidade')),
                ('document', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('rg', models.PositiveIntegerField(verbose_name='RG')),
                ('phone_number', models.CharField(max_length=11, verbose_name='telefone')),
                ('admission_date', models.DateField(default=django.utils.timezone.now, verbose_name='data de admissão')),
                ('salary', models.FloatField(verbose_name='salário')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles', verbose_name='foto')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=7, unique=True, verbose_name='placa')),
                ('model', models.CharField(max_length=100, verbose_name='modelo')),
                ('brand', models.CharField(max_length=100, verbose_name='marca')),
            ],
            options={
                'verbose_name': 'Carro',
                'ordering': ['brand'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('registration', models.CharField(max_length=255, verbose_name='inscrição estadual')),
                ('address', models.CharField(max_length=100, verbose_name='endereço')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('distance_tolerance', models.FloatField(verbose_name='tolerância de distância (km)')),
            ],
            options={
                'verbose_name': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=14, unique=True, verbose_name='CPF / CNPJ')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('address', models.CharField(max_length=100, verbose_name='endereço')),
                ('rg', models.IntegerField(verbose_name='RG')),
                ('phone_number', models.CharField(max_length=11, verbose_name='telefone')),
                ('category', models.CharField(choices=[('FREGUESES', 'FREGUESES'), ('ESPECIAL', 'ESPECIAL'), ('DEVEDORES', 'DEVEDORES')], default=0, max_length=100, verbose_name='categoria')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.car', verbose_name='carro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'ordering': ['pk'],
            },
        ),
    ]
