# Generated by Django 4.0.4 on 2022-05-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='document',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
