# Generated by Django 4.0.4 on 2022-05-05 03:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
