# Generated by Django 4.0.4 on 2022-05-03 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_employee_admission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.car'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='admission_date',
            field=models.DateField(),
        ),
    ]
