# Generated by Django 4.0.4 on 2022-05-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_client_company_employee_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='headquarters',
            field=models.BooleanField(default=False, verbose_name='matriz'),
        ),
    ]
