# Generated by Django 4.0.4 on 2022-05-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_employee_admission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='admission_date',
            field=models.DateField(default='2022-05-05'),
        ),
    ]
