# Generated by Django 4.0.4 on 2022-05-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_client_car_alter_employee_admission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, unique=True),
        ),
    ]
