# Generated by Django 4.0.4 on 2022-05-25 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_company_headquarters'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='presidente'),
        ),
        migrations.AddField(
            model_name='company',
            name='president',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='president', to=settings.AUTH_USER_MODEL, verbose_name='presidente'),
        ),
    ]
