# Generated by Django 4.0.4 on 2022-05-06 00:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_employee_admission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=7, unique=True, verbose_name='placa'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100, verbose_name='modelo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=100, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='client',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.car', verbose_name='carro'),
        ),
        migrations.AlterField(
            model_name='client',
            name='category',
            field=models.CharField(choices=[('FREGUESES', 'FREGUESES'), ('ESPECIAL', 'ESPECIAL'), ('DEVEDORES', 'DEVEDORES')], default=0, max_length=100, verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='client',
            name='document',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF / CNPJ'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='rg',
            field=models.IntegerField(verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=100, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='data de admissão'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='document',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(upload_to='profiles', verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rg',
            field=models.PositiveIntegerField(verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.FloatField(verbose_name='salário'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='speciality',
            field=models.CharField(max_length=100, verbose_name='especialidade'),
        ),
    ]
