# Generated by Django 4.0.4 on 2022-05-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_car_brand_alter_car_license_plate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Carro'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Cliente'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'empresa'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Funcionário'},
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
