# Generated by Django 4.0.4 on 2022-05-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_employee_last_login_alter_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='speciality',
            field=models.CharField(max_length=100, unique=True, verbose_name='especialidade'),
        ),
    ]
