# Generated by Django 4.0.4 on 2022-05-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_employee_document_alter_employee_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='distance_tolerance',
            field=models.FloatField(default=15, verbose_name='tolerância de distância'),
            preserve_default=False,
        ),
    ]
