# Generated by Django 4.0.4 on 2022-05-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_company_distance_tolerance'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='registration',
            field=models.CharField(default='ISENTO', max_length=255, verbose_name='Inscrição Estadual'),
            preserve_default=False,
        ),
    ]
